name: PRflow
run-name: run push
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${{github.head_ref}}" --body "hello, ${{github.actor}}"
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

