name: Manual
on: 
    workflow_dispatch:
        inputs:
            log-level:
                    type: choice
                    options:
                        - info
                        - warn
                        - error
jobs:
    print:
        runs-on: ubuntu-latest
        env: ${{ vars.USERNAME }}
        steps:
            - run: echo "helow"