name: Manual
run-name: run with @ ${{github.event}}
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.USERNAME }}
    steps:
      - run: echo "${{ env.USERNAME }}"